### ISSUE TITLE
Error: Call to undefined function create_function() 

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/demo#10]
The error: Call to undefined function create_function() 
shows up repeatedly when trying to use this module.
Creating a snapshot appears to work but shows the error
`Error
Status message
Snapshot 2023-08-22_Snapshot has been created.
Call to undefined function create_function() `

and listing snapshots does not work only showing the same error.

**Comment by argiepiano** [comment]
`create_function()` has been removed from PHP 8, so [this line](https://github.com/backdrop-contrib/demo/blob/c174fa9b548ffcaad29c8080d629d0936ea06374/demo.admin.inc#L497) need to be rewritten for it to work.

**Comment by argiepiano** [comment]
Probably a closure would work (untested)

```php
uasort($files, function($a, $b) {return ($a->filemtime < $b->filemtime);});
```

**Comment by izmeez** [comment]
The suggested change gives a new error: 
`syntax error, unexpected single-quoted string "$a, $b", expecting variable `

**Comment by argiepiano** [comment]
Be sure to copy my code exactly. It looks like you may have changed it manually, and left the quotes there. Notice that there are no quotes in my code:

uasort($files, function($a, $b) {return ($a->filemtime < $b->filemtime);});

**Comment by izmeez** [comment]
Yes, you are correct, I was just in the process of updating my comment. Your suggested change does work.

**Comment by izmeez** [comment]
How can this be marked as RTBC?

**Comment by argiepiano** [comment]
Contrib modules don't have an RTBC label, but the maintainer can see that you've tested it. Pinging @robertgarrigos, the current maintainer, to see if he can merge this.
