### ISSUE TITLE
Snapshot list does not show description

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/demo#11]
Looking at the Snapshots list the titles with time and size show but the description does not. It would be nice to see this. Thanks.

**Comment by izmeez** [comment]
Later, I realized that the description DOES show when one clicks on the file name. Maybe it would be helpful to have a note by the heading:
**Snapshot** (Click on file name for description and details)

**Comment by izmeez** [comment]
Is it possible to have the description appear immediately under the title "Snapshots"?

**Comment by robertgarrigos** [comment]
This is how backdrop renders a form element. You would need to implement your own [theme_form_element](https://docs.backdropcms.org/api/backdrop/core%21includes%21form.inc/function/theme_form_element/1) function to change that.

**Comment by izmeez** [comment]
Thanks for the link. I rather suspected it was the standard way.

**Comment by argiepiano** [comment]
> This is how backdrop renders a form element. You would need to implement your own [theme_form_element](https://docs.backdropcms.org/api/backdrop/core%21includes%21form.inc/function/theme_form_element/1) function to change that.

Actually, there is a way to include descriptions in radios and checkboxes FAPI elements. See the [explanation](https://docs.backdropcms.org/form_api#radios) in the radios FAPI reference page.  This is provided by core.

EDIT: but as @izmeez points out, that description is shown when the label is clicked.
