### ISSUE TITLE
User warning: stream_set_option() not supported

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/demo#18]
The following warning appears:
`User warning: stream_set_option() not supported for local file based stream wrappers in BackdropLocalStreamWrapper->stream_set_option() (line 700 of  ...\core\includes\stream_wrappers.inc).`

Is this a core issue or related to a call in the demo module?

**Comment by robertgarrigos** [comment]
Yes, I've seen this. Looking into it. However, I cannot find where the problem is....

**Comment by izmeez** [comment]
The module appears to be working fine, just the warning repeated 4 times (the same as the number of snapshots being displayed). May be related to reading the filenames of snapshots.

**Comment by argiepiano** [comment]
This warning is triggered when `demo` includes the info file from the `private` directory. Specifically, triggered by `parse_ini_file()` in function `demo_get_info()`.

The solution is to avoid passing the stream `private://demo/MY_FILE.info` and instead pass the absolute path of the file to `parse_ini_file()`.

PR coming

**Comment by argiepiano** [comment]
PR #20 ready for review and testing.
