### ISSUE TITLE
Better description when creating a new snapshot

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/demo#21]
When creating a new snapshot, using the same name as an existing snapshot will replace the old one. This functionality is only intuited by the description of the description field. It would be clearer to explain this functionality in the description of the title field.

**Comment by izmeez** [comment]
I agree, this concept is not clear. The help for description "Leave empty to retain the existing description when replacing a snapshot." was the first hint on replacing an existing snapshot. It isn't a feature I have made use of in the past and simply use a slight modification to the name, using a date prefix with alpha character. But, I imagine this may be useful to sites that actually use the cron reset function, just guessing. Nonetheless, I agree some more clarification on this feature would be helpful.

**Comment by robertgarrigos** [comment]
@izmeez added a PR which addresses this. Would you like to test it? Many thanks!

**Comment by izmeez** [comment]
Tested the pull request and will add my comment to it.
