### ISSUE TITLE
Confirmation step for reset form

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/demo#25]
I fell like the reset form should have a confirmation step. Right now, there is only just a message in the form, which is only one step. What would you think to have a second confirmation form after clicking the first Reset button?

**Comment by izmeez** [comment]
I didn't really think a confirmation was needed. The warning is quite clear and strong. I don't think backup_migrate has extra confirmations. Also, will a confirmation step interfere with the cron reset?

**Comment by robertgarrigos** [comment]
Right, that could be. I was looking at it now without the reset submodule. Yep, better leave it as it is now.
