### ISSUE TITLE
Version 1.06 shows as release but not as new update available

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/demo#26]
I'm not sure what is happening. The current release is 1.05 and while 1.06 shows on the available updates page it does not show as a new update. Also looking at github it appears as if new commits from yesterday were also added under that release tag. Does something need to be done to finalize it as the recommended release?

**Comment by izmeez** [comment]
A notification of my opening this issue may not have gone out. Do you know why the update is only showing as an additional release and not as an available update? It would be nice to have this fixed so it can be updated rather than having to manually install the update. Thanks.

**Comment by robertgarrigos** [comment]
There was a problem with the tag. It was 1.x-1.06 instead of 1.x-1.0.6. I modified, but I don't know if this will fix the issue. I hope so.

**Comment by argiepiano** [comment]
You'll probably need to do a new release. The problem is that b.org will not pick up the change in tag unless there is a new release

**Comment by izmeez** [comment]
I don't see the change on available updates yet even with manual recheck.

**Comment by robertgarrigos** [comment]
Thanks, @argiepiano. Done a new release. Sorry about that.

**Comment by izmeez** [comment]
The new release 1.0.7 now shows as an available update and can be installed.

However, there is now a residual problem. Is it possible to delete the tag 1.06 because it is still showing as the latest release on both the available updates and also on the backdrop project page, https://backdropcms.org/project/demo Being such an advanced number it probably won't go away unless it is stomped out. Thanks.
![demo-module-1 06-still-shows](https://github.com/backdrop-contrib/demo/assets/6208775/f2b0c77f-fabc-4538-95e7-9fb0e164b943)

**Comment by robertgarrigos** [comment]
Done

**Comment by argiepiano** [comment]
Deleting that version will probably not fix the problem, since the B-org module server has stored that version as the highest one. You'll need to ask (on Zulip) for someone with access to b-org to remove the entry from the server database.

**Comment by robertgarrigos** [comment]
Asked. Sorry about that. 😔

**Comment by izmeez** [comment]
Looks like this has all been resolved and this issue can be closed.

**Comment by izmeez** [comment]
Looks like I can close it.
