### ISSUE TITLE
Improve README file and project page.

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/demo#27]
I see how the README file is similar to the file in the Drupal module but I think it may be improved by emphasizing the two distinct uses. The first paragraph could be replaced with:

`The Demo module has two main uses: 

1. It can be used to create and restore snapshots of a site with a simple click
that can be useful when testing modules and during development.

2. With the included, optional Demo Reset module it can be used to setup a
public demonstration site; a sandbox for visitors to use, that is automatically reset
periodically using cron.`

Along the same lines the project page, https://backdropcms.org/project/demo could be changed.

It could be taken further with including the difference with it and backup_migrate as described in the forum topic, https://forum.backdropcms.org/forum/demo-module-great-snapshots-and-testing

`The demo module also saves the config files and restores them on reset, something that the backup_migrate module does not do.`

**Comment by izmeez** [comment]
Also the project page title could be enhanced similar to the Drupal project page,

`Demonstration site (Sandbox / Snapshot)`

**Comment by robertgarrigos** [comment]
I agree that the first paragraph would need to reflect its testing capability. However, the first paragraph needs to be formatted as one single paragraph of no more than 240 characters as it used as the project summary on b.org

**Comment by izmeez** [comment]
What about:

> The Demo module has two main uses. It can be used to create and restore snapshots of a site with a simple click that can be useful when testing modules and during development. Also, with the included optional Demo Reset module it can be used to setup a public demonstration site, a sandbox for visitors to use, that is automatically reset periodically using cron.

**Comment by izmeez** [comment]
Do we need more feedback on this?

**Comment by robertgarrigos** [comment]
Nop. Just some time to make the pr ;-)
