### ISSUE TITLE
Does the demo reset flush all caches?

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/demo#28]
I haven't had any issues with the demo module creating and resetting snapshots, but I wonder to myself if it is necessary to flush caches after reset or if it would be helpful to enhance the message:
`Restored site from ... .sql`
with an extra line or maybe two that states: "Restored configuration files", "Every cache cleared".

**Comment by robertgarrigos** [comment]
Demo does not clear caches, indeed. It restores the cache tables available at the time of creating the snapshot.

**Comment by izmeez** [comment]
That's what I thought initially. I guess that makes sense since they are in the database and saves recreating them.

**Comment by izmeez** [comment]
I have added this information to the wiki so this issue can be closed.
