### ISSUE TITLE
Show snapshot naming error message while preserving entry information

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/demo#31]
If the snapshot filename does not meet the requirements it would be nice if the error message can be shown while preserving the entry itself to allow user to fix it without having to do all over again. Here is a mock up.
![demo-filename-error-show-with-entry-mockup](https://github.com/backdrop-contrib/demo/assets/6208775/67f84377-1436-4d40-b4ca-8b6fe301d0f2)

**Comment by robertgarrigos** [comment]
@izmeez just posted a pr to fix this. Would you test it, please?

**Comment by izmeez** [comment]
@robertgarrigos Yes, the PR works for me. I had to manually apply the patch to test it.
