### ISSUE TITLE
Add watchdog entry at start of creating a snapshot

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/demo#35]
The demo module already creates a watchdog entry after a snapshot is restored. It would be helpful if it also creates a watchdog entry at the start of creating a snapshot so that it is part of the log that is included in the snapshot and will be visible when the snapshot is restored. This will help confirm the timing of events if one is looking back through the log later to confirm when things happened.

I appreciate this is a feature request and I have made a fork of the repo and will try to submit a PR in the next day or so to address this issue.

**Comment by robertgarrigos** [comment]
@izmeez there is pr to try out

**Comment by izmeez** [comment]
@robertgarrigos The PR works, I added a comment to the PR and I wonder if the line that is added to watchdog should be changed, removing the `for` and adding a comma?
`'Created snapshot, %filename'`
